### ISSUE TITLE
Error 500 - InvalidOperationException on install

### ISSUE THREAD

**Issue by Skip75** [certera-io/certera#33]
Hello

I'm trying to install it.
I've downloaded, unzipped, set correct changes (chmod, port binding permission, etc...) since I'm using Linux.
Then started the process. No issue so far. (Certificate discovery service starting., etc...)

Then I connect to web server and then... I have the issue :
`500 Internal Server Error`
and below logs in application side :
```
Mar 20 00:17:15 pki-certera certera[16545]: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
Mar 20 00:17:15 pki-certera certera[16545]:       An unhandled exception has occurred while executing the request.
Mar 20 00:17:15 pki-certera certera[16545]: System.InvalidOperationException: Cannot create instance of type 'System.String' because it is missing a public parameterless constructor.
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Configuration.ConfigurationBinder.CreateInstance(Type type)
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance, BinderOptions options)
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance, Action`1 configureOptions)
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Options.NamedConfigureFromConfigurationOptions`1.<>c__DisplayClass1_0.<.ctor>b__0(TOptions options)
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
Mar 20 00:17:15 pki-certera certera[16545]: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[3]
Mar 20 00:17:15 pki-certera certera[16545]:       An exception was thrown attempting to execute the error handler.
Mar 20 00:17:15 pki-certera certera[16545]: System.InvalidOperationException: Cannot create instance of type 'System.String' because it is missing a public parameterless constructor.
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Configuration.ConfigurationBinder.CreateInstance(Type type)
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance, BinderOptions options)
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance, Action`1 configureOptions)
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Options.NamedConfigureFromConfigurationOptions`1.<>c__DisplayClass1_0.<.ctor>b__0(TOptions options)
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
Mar 20 00:17:15 pki-certera certera[16545]: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Server.Kestrel[13]
Mar 20 00:17:15 pki-certera certera[16545]:       Connection id "0HMG9VN2BQ4QO", Request id "0HMG9VN2BQ4QO:00000001": An unhandled exception was thrown by the application.
Mar 20 00:17:15 pki-certera certera[16545]: System.InvalidOperationException: Cannot create instance of type 'System.String' because it is missing a public parameterless constructor.
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Configuration.ConfigurationBinder.CreateInstance(Type type)
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance, BinderOptions options)
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance, Action`1 configureOptions)
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Options.NamedConfigureFromConfigurationOptions`1.<>c__DisplayClass1_0.<.ctor>b__0(TOptions options)
Mar 20 00:17:15 pki-certera certera[16545]:    at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)

```

Any idea ?

**Comment by Skip75** [comment]
Ok, found. It was an issue in the config file. The JSON was not expecting an array.
```
{
  "AllowedRemoteIPAddresses": {
    "AdminUI": [
      "X.X.X.X",
      "X.X.X.X/24"
    ],
    "API": ""
...
```
After changing it, no more issue.
